module.exports = {
  ccsa: {
    output: {
      mode: "tags",
      client: "react-query",
      target: "./src/types/generated/strapi.ts",
      mock: false,
      clean: true,
      prettier: true,
      override: {
        mutator: {
          path: "./src/services/api/index.ts",
          name: "API",
        },
        query: {
          useQuery: true,
          useMutation: true,
          signal: true,
        },
      },
    },
    input: {
      target: "../cms/src/extensions/documentation/documentation/1.0.0/full_documentation.json",
      filters: {
        tags: [
          "Project",
          "Dataset",
          "Layer",
          "Country",
          "Category",
          "Pillar",
          "Sdg",
          "Download-email",
          "Objective",
          "Organization-type",
          "Other-tool",
          "Other-tools-category",
          "Project-edit-suggestion",
          "Project-field-metadata",
          "Project-status",
          "Types-of-funding",
          "Tool-edit-suggestion",
          "Dataset-value",
          "Dataset-edit-suggestion",
          "Collaborator",
          "Collaborator-edit-suggestion",
          "User",
          "Users-Permissions - Auth",
          "Users-Permissions - Users & Roles",
          "Welcome-message",
          "World-country",
        ],
      },
    },
  },
};
