import { Metadata } from "next";

import NewCollaboratorsForm from "@/containers/collaborators/new";

export const metadata: Metadata = {
  title: "Create new collaborator | Caribbean Climate smart map",
  description: "Generated by create next app",
};

export default function NewCollaboratorPage() {
  return (
    <div className="relative z-10 h-full w-full bg-white">
      <NewCollaboratorsForm />
    </div>
  );
}
