import { Metadata, Viewport } from "next";

import CollaboratorsForm from "@/containers/collaborators/form";

export const metadata: Metadata = {
  title: "Create new collaborator | Caribbean Climate smart map",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: 1000,
  initialScale: 1,
};

export default function CollaboratorPage() {
  return (
    <div className="relative z-10 h-full w-full bg-white">
      <CollaboratorsForm />
    </div>
  );
}
