import { Metadata } from "next";

import CollaboratorsForm from "@/containers/collaborators/form";

export const metadata: Metadata = {
  title: "Create new collaborator | Caribbean Climate smart map",
  description: "Generated by create next app",
  viewport: "width=1000, initial-scale=1",
};

export default function CollaboratorPage() {
  return (
    <div className="relative z-10 h-full w-full bg-white">
      <CollaboratorsForm />
    </div>
  );
}
