import { Metadata, Viewport } from "next";

import ProjectForm from "@/containers/projects/form";

export const metadata: Metadata = {
  title: "Create / edit a project | Caribbean Climate smart map",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: 1000,
  initialScale: 1,
};

export const viewport: Viewport = {
  width: 1000,
  initialScale: 1,
};

export default function NewProjectsPage() {
  return (
    <div className="relative z-10 h-full w-full bg-white">
      <ProjectForm />
    </div>
  );
}
