import { Metadata } from "next";

import ProjectForm from "@/containers/projects/form";

export const metadata: Metadata = {
  title: "Create / edit a project | Caribbean Climate smart map",
  description: "Generated by create next app",
  viewport: "width=1000, initial-scale=1",
};

export default function NewProjectsPage() {
  return (
    <div className="relative z-10 h-full w-full bg-white">
      <ProjectForm />
    </div>
  );
}
