import "@/styles/globals.css";
import "mapbox-gl/dist/mapbox-gl.css";

import { PropsWithChildren } from "react";

import type { Metadata } from "next";

import LayoutProviders from "./layout-providers";

export const metadata: Metadata = {
  title: "CCSA",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: PropsWithChildren) {
  return (
    <LayoutProviders>
      <html lang="en">
        <body>{children}</body>
      </html>
    </LayoutProviders>
  );
}
