import { Metadata, Viewport } from "next";

import PasswordUpdate from "@/components/forms/password-update";

export const metadata: Metadata = {
  title: "Update Password | Caribbean Climate smart map",
  description: "Generated by create next app",
  viewport: "width=1000, initial-scale=1",
};

export const viewport: Viewport = {
  width: 1000,
  initialScale: 1,
};

export default function UpdatePasswordPage() {
  return (
    <>
      <div className="space-y-2 py-10">
        <h1 className="pt-10 text-3xl font-bold -tracking-[0.0375rem]">Reset your password</h1>
      </div>
      <PasswordUpdate />
    </>
  );
}
