import { Metadata } from "next";

import NewToolForm from "@/containers/other-tools/new";

export const metadata: Metadata = {
  title: "Create new tool | Caribbean Climate smart map",
  description: "Generated by create next app",
};

export default function NewToolPage() {
  return (
    <div className="relative z-10 h-full w-full bg-white">
      <NewToolForm />
    </div>
  );
}
