[tool.ruff]
line-length = 100
extend-include = ["*.ipynb"]

[tool.ruff.lint]
select = [
    "E", # pycodestyle errors
    "W", # pycodestyle warnings
    "F", # flake8
    "C", # flake8-comprehensions
    "B", # flake8-bugbear
    "N", # Naming conventions
    "I", # isort
]

ignore = []
