[tool.ruff]
select = [
    "D1",   # pydocstyle errors
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "F",    # flake8
    "C",    # flake8-comprehensions
    "B",    # flake8-bugbear
    "N",    # Naming conventions
    "I",    # isort
]
line-length = 100
ignore = [
    "D100",
    "D104",
]
extend-include = ["*.ipynb"]
