import { Metadata } from "next";

import DashboardContent from "@/containers/dashboard";

export const metadata: Metadata = {
  title: "Dashboard | Caribbean Climate smart map",
  description: "Generated by create next app",
  viewport: "width=1000, initial-scale=1",
};

export default function DashboardPage() {
  return (
    <div className="w-full">
      <DashboardContent />
    </div>
  );
}
