import { Metadata } from "next";

import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

import PersonalData from "@/containers/personal-data";
import DatasetsChanges from "@/containers/datasets-changes";

export const metadata: Metadata = {
  title: "Dashboard | Caribbean Climate smart map",
  description: "Generated by create next app",
};

export default function DashboardPage() {
  return (
    <div className="w-full">
      <Tabs defaultValue="changes" className="w-full divide-y-2 divide-gray-300/20">
        <TabsList className="p-4 sm:px-10 md:px-24 lg:px-32">
          <TabsTrigger value="changes">Pending changes</TabsTrigger>
          <TabsTrigger value="account">Personal data</TabsTrigger>
        </TabsList>
        <TabsContent value="changes">
          <DatasetsChanges />
        </TabsContent>
        <TabsContent value="account">
          <PersonalData />
        </TabsContent>
      </Tabs>
    </div>
  );
}
