import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard | Caribbean Climate smart map",
  description: "Generated by create next app",
};

export default function DashboardPage() {
  return (
    <>
      <h1 className="py-10 text-3xl font-bold -tracking-[0.0375rem]">Dashboard</h1>
    </>
  );
}
